### ISSUE TITLE
Can not found SR-STE implementation in project.

### ISSUE THREAD

**Issue by hopef** [zyxxmu/LBC#5]
Hi author,

Thanks for your excellent project.
How do I reproduce the SR-STE result in your project? Could you share the code with me? Thanks a lot.
As far as I know, SR-STE trained without LabelSmoothing.

**Comment by zyxxmu** [comment]
You can find the code of SR-STE at https://github.com/NM-sparsity/NM-sparsity.

**Comment by hopef** [comment]
Thanks for your reply. !
